### ISSUE TITLE
let vs. let!

### ISSUE THREAD

**Issue by sebastiancaraballo** [rootstrap/tech-guides#75]
**Affected Guide:**
https://github.com/rootstrap/tech-guides/blob/master/ruby/rspec/tutorial.md

**Describe your motive to discuss:**
When learning RSpec for the first time, it may be confusing to understand what the use of `!` with `let` variables is for.

**Describe the solution you propose**
 I think it would be helpful to add an explanation of how to use it and add some examples.

**Comment by AgostinaDev** [comment]
I think it's a great idea.

It happened to me when I started learning RoR & RSpec that I saw parts of the code that had a let with a bang and some other places had a let without a bang.

I was kind of confused because I wasn't sure when to add the bang, so I just tried to copy from code that was already there. Sometimes the example I took was wrong, so it ended up being corrected during Code Review. I kept making mistakes with the misuse of the bang until I started connecting the dots.

With bang: eager initialization of the let, assigns the value immediately when loaded.
Without bang: lazy initialization of the let, assigns the value when the let is called.

I Identified some of these cases:
Add bang:
- If you need to trigger an insertion into the database before running the it block & the let is _not_ being called from another let with a bang.
  - Not adding the bang in these cases may cause the tests to fail because it may get a null value (idk if it's loaded asynchronously or what)

Avoid bang:
- If the value is something that you keep in memory & does not need to be inserted in the database before executing the it block.
- If you need to trigger an insertion into the database & the let is being called from another let with a bang.

Example of misuse:
[<img width="801" alt="imagen" src="https://user-images.githubusercontent.com/80283482/190444855-79dfd361-cb67-484b-b091-f2d2a53c3b81.png">](https://github.com/rootstrap/forecast/blob/develop/spec/services/calculators/dashboard/people_service_spec.rb#L18)

Corrected (remove the bang because person1 is called from a let with a bang):
<img width="755" alt="imagen" src="https://user-images.githubusercontent.com/80283482/190446350-7860f554-ec17-4d5f-baf4-9c664080d54f.png">


Example of misuse:
[<img width="429" alt="imagen" src="https://user-images.githubusercontent.com/80283482/190445459-8f267d91-4aec-4ef1-b90b-c176a41ed3c4.png">](https://github.com/rootstrap/forecast/blob/develop/spec/forms/person_form_spec.rb#L8)

Corrected (remove the bang because build() works in memory:

<img width="414" alt="imagen" src="https://user-images.githubusercontent.com/80283482/190445754-5b25e3f5-6222-4192-9222-f0fc87209dda.png">

**Comment by adlamas** [comment]
I would also add this situation that, at least for me, is the most usual.

I always try to write the `let` block without the `!` if I have a variable whose value needs to be changed over the course of the testing, in order to test different contexts.
For example in the images that Agos put, a person that needs to belong, in a context, to the engineering department but, in another one, to the HR department

**Comment by claramaffei** [comment]
I think it's a great idea to clarify the use of the bang. It still happens to me sometimes, and as Tina said, it may happen that you look in another part of the code and it is not well implemented.

Good examples to better understand when it should be used and when it shouldn't.

Another topic that could be interesting to raise is that using `let` (to create, build, and also to define simple variables like dates) is better than creating new variables or adding `before` blocks.
